### ISSUE TITLE
Swift package name conflicts

### ISSUE THREAD

**Issue by batesyuk** [glassfy/ios-sdk#3]
When installing using SPM Xcode picks the package name up as ios-sdk

This is really generic and is:
1. Hard to reason in the list of packages in xcode
2. Causing conflicts with other packages that are names the same, as Xcode doesn't seem smart enough to differentiate between the two packages throwing the following error. "The project already depends on: ios-sdk"

An example of one conflict with a package doing the same thing is: [UXCam](https://github.com/uxcam/ios-sdk)

**Comment by lgarbo** [comment]
Hi, to solve the issue, you can use `https://github.com/glassfy/glassfy-ios-sdk` as location in SPM

**Comment by Nielssg** [comment]
@lgarbo could this piece of information possibly be added to the iOS installation documentation (e.g. troubleshooting)? I've had a similar issue where Spotify's iOS SDK is also called ios-sdk, it would be great to have the information available in the documentation instead of trying to scour GitHub for information.
